[versions]
agp = "8.1.0"
kotlin = "1.7.20"

coreKtx = "1.6.0"
coroutines = "1.6.4"
startup = "1.0.0"

ktorClient = "2.3.12"
androidxCamera = "1.2.3"
androidExoPlayer = "2.16.0"
sqldelight = "1.5.5"

jdcrDevBase = "0.3.5-SNAPSHOT"
jdcrLog = "1.3.2-SNAPSHOT"
jdcrDatabase = "0.0.0"
jdcrHttp = "0.4.0-SNAPSHOT"
jdcrMediaPlayer = "0.4.2-SNAPSHOT"
jdcrPermission = "0.9.1-SNAPSHOT"
jdcrCameraBase = "1.2.8-SNAPSHOT"
jdcrCameraGesture = "1.2.8-SNAPSHOT"
jdcrCameraQRCode = "1.2.8-SNAPSHOT"
jdcrBluetooth = "0.9.6-SNAPSHOT"
jdcrFile = "0.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktorClient" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktorClient" }
ktor-client-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktorClient" }
ktor-client-serialization = { group = "io.ktor", name = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorClient" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktorClient" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktorClient" }
ktor-client-encoding = { group = "io.ktor", name = "io.ktor:ktor-client-encoding", version.ref = "ktorClient" }
androidx-camera = { group = "androidx.camera", name = "camera-camera2", version.ref = "androidxCamera" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "androidxCamera" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "androidxCamera" }
android-exoplayer = { group = "com.google.android.exoplayer", name = "exoplayer", version.ref = "androidExoPlayer" }
sqldelight-runtime = { group = "com.squareup.sqldelight", name = "runtime", version.ref = "sqldelight" }
sqldelight-android-driver = { group = "com.squareup.sqldelight", name = "android-driver", version.ref = "sqldelight" }

jdcr-dev-base = { group = "com.github.ljwx", name = "JdcrDevBase", version.ref = "jdcrDevBase" }
jdcr-log = { group = "com.github.ljwx.jdcrlog", name = "jdcrlog-android", version.ref = "jdcrLog" }
jdcr-database = { group = "com.github.ljwx", name = "JdcrDatabase", version.ref = "jdcrDatabase" }
jdcr-http = { group = "com.github.ljwx", name = "jdcrhttp", version.ref = "jdcrHttp" }
jdcr-media-player = { group = "com.github.ljwx", name = "mediaplayer", version.ref = "jdcrMediaPlayer" }
jdcr-permission = { group = "com.github.ljwx", name = "JdcrPermissions", version.ref = "jdcrPermission" }
jdcr-camera-base = { group = "com.github.ljwx.CameraCommon", name = "camerabase", version.ref = "jdcrCameraBase" }
jdcr-camera-gesture = { group = "com.github.ljwx.CameraCommon", name = "cameragesture", version.ref = "jdcrCameraGesture" }
jdcr-camera-qrcode = { group = "com.github.ljwx.CameraCommon", name = "qrcode", version.ref = "jdcrCameraQRCode" }
jdcr-bluetooth = { group = "com.github.ljwx", name = "jdcrbluetooth", version.ref = "jdcrBluetooth" }
jdcr-file = { group = "com.github.ljwx", name = "JdcrFile", version.ref = "jdcrFile" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqldelight" }
