[versions]
agp = "8.1.0"
kotlin = "1.7.20"

coreKtx = "1.6.0"
coroutines = "1.6.4"
startup = "1.0.0"

jdcrLog = "1.3.1-SNAPSHOT"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }
jdcr-log = { group = "com.github.ljwx.jdcrlog", name = "jdcrlog-android", version.ref = "jdcrLog" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
